export const highlightColor = 'orange-500'
export const darkHighlightColor = 'yellow-300'
export const textColor = 'neutral-800'
export const darkTextColor = 'neutral-200'
export const subtitleColor = 'neutral-500'
